-- MySQL Script generated by MySQL Workbench
-- Fri Feb 21 19:56:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Marcas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_Marcas_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Modelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Modelos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `id_marca` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_Modelos_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_marca_idx` (`id_marca` ASC) VISIBLE,
  CONSTRAINT `id_marca`
    FOREIGN KEY (`id_marca`)
    REFERENCES `mydb`.`Marcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoVehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoVehiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_TipoVehiculo_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TiposCombustible`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TiposCombustible` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_TiposCombustible_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehiculos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  `no_chasis` VARCHAR(17) NOT NULL,
  `no_motor` VARCHAR(20) NOT NULL,
  `no_placa` VARCHAR(10) NOT NULL,
  `id_tipoVehiculo` INT NOT NULL,
  `id_marca` INT NOT NULL,
  `id_modelo` INT NOT NULL,
  `id_tipo_combustible` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idVehiculos_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `no_chasis_UNIQUE` (`no_chasis` ASC) VISIBLE,
  UNIQUE INDEX `no_motor_UNIQUE` (`no_motor` ASC) VISIBLE,
  UNIQUE INDEX `no_placa_UNIQUE` (`no_placa` ASC) VISIBLE,
  INDEX `id_TipoVehiculo_idx` (`id_tipoVehiculo` ASC) VISIBLE,
  INDEX `id_Modelo_idx` (`id_modelo` ASC) VISIBLE,
  INDEX `id_TipoCombustible_idx` (`id_tipo_combustible` ASC) VISIBLE,
  INDEX `id_marca_idx` (`id_marca` ASC) VISIBLE,
  CONSTRAINT `id_marca`
    FOREIGN KEY (`id_marca`)
    REFERENCES `mydb`.`Modelos` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_tipo_vehiculo`
    FOREIGN KEY (`id_tipoVehiculo`)
    REFERENCES `mydb`.`TipoVehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_modelo`
    FOREIGN KEY (`id_modelo`)
    REFERENCES `mydb`.`Modelos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_tipo_combustible`
    FOREIGN KEY (`id_tipo_combustible`)
    REFERENCES `mydb`.`TiposCombustible` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `cedula` VARCHAR(12) NOT NULL,
  `no_tarjeta_cr` VARCHAR(16) NOT NULL,
  `limite_credito` DECIMAL(15,2) NOT NULL,
  `tipo_persona` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_Clientes_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(12) NOT NULL,
  `tanda_labor` VARCHAR(100) NOT NULL,
  `porciento_comision` DECIMAL(5,2) NULL,
  `fecha_ingreso` DATE NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_Empleados_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inspecciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inspecciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_vehiculos` INT NOT NULL,
  `id_clientes` INT NOT NULL,
  `tiene_ralladuras` TINYINT NOT NULL,
  `cantidad_combustible` VARCHAR(45) NOT NULL,
  `tiene_gomas_repuesto` TINYINT NOT NULL,
  `tiene_gato` TINYINT NOT NULL,
  `tiene_roturas_cristal` TINYINT NOT NULL,
  `estado_gomas` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `id_empleado` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_Inspecciones_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_Vehiculos_idx` (`id_vehiculos` ASC) VISIBLE,
  INDEX `id_Clientes_idx` (`id_clientes` ASC) VISIBLE,
  INDEX `id_Empleados_idx` (`id_empleado` ASC) VISIBLE,
  CONSTRAINT `id_vehiculo`
    FOREIGN KEY (`id_vehiculos`)
    REFERENCES `mydb`.`Vehiculos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_clientes`)
    REFERENCES `mydb`.`Clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `mydb`.`Empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RentaDevolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RentaDevolucion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_empleados` INT NOT NULL,
  `id_vehiculo` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `fecha_renta` DATE NOT NULL,
  `fecha_devolucion` DATE NOT NULL,
  `monto_por_dia` DECIMAL(20,2) NOT NULL,
  `cantidad_dias` INT NOT NULL,
  `comentario` TEXT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_Renta_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `id_Empleados_idx` (`id_empleados` ASC) VISIBLE,
  INDEX `id_Vehiculos_idx` (`id_vehiculo` ASC) VISIBLE,
  INDEX `id_Clientes_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `id_empleado`
    FOREIGN KEY (`id_empleados`)
    REFERENCES `mydb`.`Empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_vehiculo`
    FOREIGN KEY (`id_vehiculo`)
    REFERENCES `mydb`.`Vehiculos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`Clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
